let szamlalo = 1;

let kerdesekValaszok = [
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Minek a rövidítése a HTML?',
        valaszok: [
            'HyperType Markup Language',
            'HyperText Markup Literature',
            'HyperText Markup Language',
            'HyperText Mark Language',
        ],
        joValaszok: ['HyperText Markup Language'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Mit jelent az, hogy hiperszöveg?',
        valaszok: [
            'Semmit, csak jól hangzik.',
            'Sima szöveg más erőforrásokra mutató hivatkozásokkal.',
            'Lehetővé teszi képek közvetlen beszúrását a szövegbe.',
            'Csak Word dokumentumok szerkesztésére használható szöveg.',
        ],
        joValaszok: ['Sima szöveg más erőforrásokra mutató hivatkozásokkal.'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Mit jelent az, hogy jelölőnyelv?',
        valaszok: [
            'A tartalom részeit elemekbe (<span class="kiemel">element</span>), címkék (<span class="kiemel">tag</span>) közé csomagolja.',
            'A szöveg részeinek kijelölése után fel tudom cserélni őket.',
            'Kijelöli azokat a szimbólumokat, amelyeket használhatunk.',
            'Kijelöli a szövegnek azt a részeit, amelyeket egyedül szerkeszthetünk.',
        ],
        joValaszok: [
            'A tartalom részeit elemekbe (<span class="kiemel">element</span>), címkék (<span class="kiemel">tag</span>) közé csomagolja.',
        ],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Hogyan jelöljük, ha az oldal a HTML5 kódolást használja?',
        valaszok: [
            '&lt;DOCTYPE html&gt;',
            '&lt;DOCTYPE! html&gt;',
            '&lt;!DOCTYPE html&gt;',
            'Nincs külön jelölés.',
        ],
        joValaszok: ['&lt;!DOCTYPE html&gt;'],
    },
    {
        tipus: 'checkBox',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Melyik létező HTML elem?',
        valaszok: [
            '&lt;head&gt;',
            '&lt;foot&gt;',
            '&lt;body&gt;',
            '&lt;feet&gt;',
            '&lt;leg&gt;',
        ],
        joValaszok: ['&lt;head&gt;', '&lt;body&gt;'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Melyik nem kötelezően megadandó elem?',
        valaszok: [
            '&lt;html&gt;&lt;/html&gt;',
            '&lt;head&gt;&lt;/head&gt;',
            '&lt;title&gt;&lt;/title&gt;',
            '&lt;style&gt;&lt;/style&gt;',
            '&lt;body&gt;&lt;/body&gt;',
        ],
        joValaszok: ['&lt;style&gt;&lt;/style&gt;'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Minden elemnek van nyitó- és zárócímkéje?',
        valaszok: ['igaz', 'hamis'],
        joValaszok: ['hamis'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Melyik nem üres elem?',
        valaszok: [
            '&lt;hr /&gt;',
            '&lt;br /&gt;',
            '&lt;a /&gt;',
            '&lt;img /&gt;',
            '&lt;meta /&gt;',
        ],
        joValaszok: ['&lt;a /&gt;'],
    },
    {
        tipus: 'checkBox',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Mi nem igaz az üres elemre?',
        valaszok: ['Van nyitócímkéje.', 'Van zárócímkéje.', 'Van tartalma.'],
        joValaszok: ['Van zárócímkéje.', 'Van tartalma.'],
    },
    {
        tipus: 'checkBox',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Mi igaz egy blokkszintű elemre?',
        valaszok: [
            'Mindig új sort kezd.',
            'Csak annyi helyet foglal el, amennyi szükséges, többet nem.',
            'A böngésző automatikusan tesz egy kis margót az elem elé és mögé.',
            'Általában van tartalma.',
            'Nem ágyazhatóak egymásba.',
        ],
        joValaszok: [
            'Mindig új sort kezd.',
            'A böngésző automatikusan tesz egy kis margót az elem elé és mögé.',
            'Általában van tartalma.',
        ],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Mi nem igaz egy beágyazott elemre?',
        valaszok: [
            'Mindig új sort kezd.',
            'Csak annyi helyet foglal el, amennyi szükséges, többet nem.',
            'Egy beágyazott elem nem tartalmazhat egy blokkszintű elemet.',
            'Általában van tartalma.',
        ],
        joValaszok: ['Mindig új sort kezd.'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Melyik állítás nem igaz az attribútumokra?',
        valaszok: [
            'Mindig az elem zárócímkéjében találhatóak.',
            'Rendszerint név="érték" (<span class="kiemel">name="value"</span>) formában írjuk őket.',
            'Vannak logikai attribútumok is.',
            'Minden HTML elemnek lehetnek.',
        ],
        joValaszok: ['Mindig az elem zárócímkéjében találhatóak.'],
    },
    {
        tipus: 'checkBox',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Melyik nem létező attribútum?',
        valaszok: [
            'width',
            'height',
            'weight',
            'alt',
            'length',
            'src',
            'title',
        ],
        joValaszok: ['weight', 'length'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_001.jpg',
        kerdes: 'Hogyan jelöljük a HTML-ben a kommentet?',
        valaszok: [
            '/* */',
            '*/ /*',
            '&lt;-- --&gt;',
            '&lt;-- --!&gt;',
            '&lt;!-- --!&gt;',
            '&lt;!-- --&gt;',
            '&lt;--! --&gt;',
        ],
        joValaszok: ['&lt;!-- --&gt;'],
    },
    {
        tipus: 'radioButton',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_003.jpg',
        kerdes: 'Melyik HTML elemnek a leszármazottja és melyiknek a testvére a &lt;head&gt; elem?',
        valaszok: [
            '&lt;html&gt; és &lt;title&gt;',
            '&lt;html&gt; és &lt;body&gt;',
            '&lt;body&gt; és &lt;html&gt;',
            'Nincsenek ilyen elemek.',
        ],
        joValaszok: ['&lt;html&gt; és &lt;body&gt;'],
    },
    {
        tipus: 'checkBox',
        osztaly: `feladat_${szamlalo++}`,
        kep: './images/kep_003.jpg',
        kerdes: 'Melyik nem metaadato(ka)t tartalmazó elem?',
        valaszok: [
            'meta',
            'base',
            'href',
            'style',
            'link',
            'src',
            'script',
            'title',
        ],
        joValaszok: ['href', 'src'],
    },
];
